### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/thanks#43]
Related to https://github.com/rust-lang-nursery/thanks/issues/42, an explicit opt out is a good call.

This information is public, as in, it's in the github history for anyone to see, but if someone doesn't want their name on this page for some reason, we should respect that.

I am happy to do this manually for now, but it's gonna need to be automated in some fashion.

**Comment by steveklabnik** [comment]
Blocked on infrastructure work that's part of https://github.com/rust-lang-nursery/thanks/issues/8

**Comment by jmatraszek** [comment]
I could work on that (cannot commit to work on higher priority issues right now like fixing support for multiple projects due to a lack of time).

I think we should do the following:
1. finally normalize the database and pull the authors out of commits to their own table;
2. add a new binary (e.g. `opt-out`) that will mark the author as opted-out (or create a new one marked as opted-out from the start -- if someone wants to opt-out before their project is added to thanks);
3. fix front-end to respect that.

Going with this approach we would still have the names/emails in the database (just not show them in the front-end), but I think it is acceptable as this data is publicly available in the repos on GitHub. If not, then we should investigate some other solution.

**Comment by steveklabnik** [comment]
> finally normalize the database and pull the authors out of commits to their own table;

💯 

> add a new binary (e.g. opt-out) that will mark the author as opted-out

💯 

> fix front-end to respect that.

👍 , luckily this shouldn't need any _real_ front-end work, just modifying queries, which you'll have to do anyway for 1.

>  I think it is acceptable as this data is publicly available in the repos on GitHub

Yes, this is about ease of getting the information; in my experience, this would be fine. Nobody has straight-up wanted to opt out yet, so I can't consult anyone directly.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang-nursery/thanks/pull/72 closes this!
