### ISSUE TITLE
Make "release number" on a "thanks" page a clickable link to that release on Changelog

### ISSUE THREAD

**Issue by 62mkv** [rust-lang-nursery/thanks#79]
Hi

Someone posted a link to a https://thanks.rust-lang.org/rust/1.15.1 page and my first impulse was to see what exactly have those 2 gentlemen done (in the 1.15.1 release)

However, it appeared to be not so easy a task! Nowhere on the thanks.rust-lang.org (or rust-lang.org itself, for the matter) could I find a Rust release history with detailed links for every version. I am sure it's possible to find, but why make things so complicated ? 

Hence my suggestion: make release numbers in "thanks" pages clickable links to a corresponding section on the Changelog! 

Thanks to all tremendous rustaceans!

**Comment by russmack** [comment]
Is the rust-lang/rust/RELEASES.md generated manually?  The anchors rendered in github include the version and date, the latter not matching the tag date, so linking to the version anchor would be easier if the date was put on the line below (do other sites link to these?), as the version is readily available in rust-lang-nursery/thanks.  Otherwise, linking to eg https://github.com/rust-lang/rust/compare/1.15.0...1.15.1 would be easy, but between some releases results in "This comparison is big!".

**Comment by steveklabnik** [comment]
Yes, it is entirely manual.

At the same time, creating a new release in thanks is also manual, so it's not a big deal to give it the right link.

**Comment by steveklabnik** [comment]
Steps to do this:

1. write a migration to:
    1. add a nullable column to releases, 'link'
    2. backfill the existing releases properly
    3. make the column non-nullable
2. modify the new-release command to take the link as a command-line argument.

**Comment by russmack** [comment]
I'll take this if that suits.

**Comment by steveklabnik** [comment]
That'd be great!
